In [2]:
import numpy as np

In [4]:
l = [1,2,3,4]

In [5]:
ar = np.array(l)               # List to array convert

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [9]:
b = np.matrix(l)                # List to matrix

In [10]:
b

matrix([[1, 2, 3, 4]])

In [11]:
np.asarray(b)      # It will not convert matrix into array

array([[1, 2, 3, 4]])

In [12]:
a = np.array(l)

In [13]:
a

array([1, 2, 3, 4])

In [14]:
c = a

In [15]:
c

array([1, 2, 3, 4])

In [16]:
c[0] = 100

In [17]:
c

array([100,   2,   3,   4])

In [18]:
a

array([100,   2,   3,   4])

In [19]:
d = np.copy(a)

In [20]:
a[1] = 500

In [21]:
a

array([100, 500,   3,   4])

In [22]:
d

array([100,   2,   3,   4])

In [23]:
np.fromfunction(lambda i , j : i == j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [24]:
np.fromfunction(lambda i , j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [26]:
p = (i*i for i in range(5))

In [28]:
np.fromiter(p , int)

array([ 0,  1,  4,  9, 16])

In [33]:
np.fromstring("456 987" , sep= " ")

array([456., 987.])

In [36]:
np.fromstring("4,5" , sep= ",")

array([4., 5.])

In [37]:
# Numpy DataTypes

In [38]:
l = [2,3,4,5,6]

In [39]:
ar = np.array(l)

In [40]:
ar

array([2, 3, 4, 5, 6])

In [41]:
ar.ndim

1

In [42]:
ar.size

5

In [43]:
ar.dtype

dtype('int64')

In [44]:
list(range(5))

[0, 1, 2, 3, 4]

In [45]:
list(range(0.1 ,5))

TypeError: 'float' object cannot be interpreted as an integer

In [46]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [47]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [48]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [49]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [50]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [52]:
ar4 = np.zeros((3,4,2,3))

In [53]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [54]:
np.ones(4)

array([1., 1., 1., 1.])

In [55]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
on =np.ones((2,3,2))

In [57]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [58]:
on *4


array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [59]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [60]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
np.linspace(2,4 , 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [62]:
np.logspace(2,5 , 10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [6]:
arr = np.random.randn(3,4)

In [7]:
import pandas as pd

In [8]:
pd.DataFrame(arr)

0         1         2         3
0  0.487042 -1.676096 -1.068566  1.562376
1 -0.693415  0.484687  0.201654 -0.899768
2 -0.821806 -0.124901 -0.403534  0.376658

In [9]:
np.random.rand(3,4)

array([[0.71181003, 0.02400912, 0.93378539, 0.80505403],
       [0.60807547, 0.49817559, 0.18508972, 0.2266295 ],
       [0.23420324, 0.02587574, 0.23740403, 0.23261398]])

In [11]:
np.random.randint(1 ,100 ,(3,4))

array([[68, 23, 48, 54],
       [25, 52, 58, 18],
       [38, 68, 20, 23]])

In [12]:
arr = np.random.rand(3,4)

In [13]:
arr

array([[0.74776053, 0.06530661, 0.93250078, 0.64859985],
       [0.93212919, 0.02965043, 0.19706935, 0.99042852],
       [0.16760541, 0.00214337, 0.11844213, 0.67820162]])

In [14]:
arr.reshape(6,2)

array([[0.74776053, 0.06530661],
       [0.93250078, 0.64859985],
       [0.93212919, 0.02965043],
       [0.19706935, 0.99042852],
       [0.16760541, 0.00214337],
       [0.11844213, 0.67820162]])

In [16]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [17]:
arr1

array([[2, 2, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [18]:
arr2

array([[1, 2, 1],
       [1, 2, 2],
       [1, 1, 1]])

In [19]:
arr1+arr2

array([[3, 4, 3],
       [3, 3, 3],
       [3, 3, 2]])

In [20]:
arr1-arr2

array([[ 1,  0,  1],
       [ 1, -1, -1],
       [ 1,  1,  0]])

In [21]:
arr1*arr2

array([[2, 4, 2],
       [2, 2, 2],
       [2, 2, 1]])

In [22]:
arr1/arr2

array([[2. , 1. , 2. ],
       [2. , 0.5, 0.5],
       [2. , 2. , 1. ]])

In [23]:
arr1@arr2

array([[ 6, 10,  8],
       [ 4,  7,  5],
       [ 5,  9,  7]])

In [24]:
# Numpy Brodcasting